### ISSUE TITLE
esbook not building correctly when setting nested outdir

### ISSUE THREAD

**Issue by ZarcoNontol** [dxos/esbuild-server#14]
Steps:

- go to https://github.com/dxos/demos
- yarn install
- Modify outdir:
```
overrides: {
    sourcemap: 'inline',
    outdir: './dist/demos/'
  }
```
- yarn build

Current behaviour:

<img width="391" alt="Screen Shot 2022-02-04 at 15 19 54" src="https://user-images.githubusercontent.com/17819818/152582337-efbc4020-0876-4ee9-a8ae-4c5e301a4bdc.png">

Expected behaviour:

<img width="362" alt="Screen Shot 2022-02-04 at 15 22 00" src="https://user-images.githubusercontent.com/17819818/152582436-7df02cfd-c39c-4da6-a82a-d223b28c2b97.png">

`index.html` should be at `index.js` level

**Comment by Marik-D** [comment]
`outdir` should be specified at the top level:

```
  overrides: {
    sourcemap: 'inline',
  },
  outdir: './dist/demos'
  ```
  
there're couple improvements we could make there:

- [ ] Error if `outdir` is specified in overrides.
- [ ] Support nested directories in `outdir`, right now esbuild-server fails to create the output directory.

cc @ZarcoNontol
